In [1]:
# Normal stack of pandas, numpy, matplotlib and seaborn
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns
from tqdm import * #progress bar

import os
import json

%matplotlib inline

## Load Factual categories taxonomy

http://developer.factual.com/working-with-categories/

In [2]:
root = 'data/'
categories = pd.read_json(root + 'factual_en_taxonomy.json', orient='index')
categories["parents"] = categories["parents"].apply(lambda x: ", ".join(x))
categories

abstract                                            label parents
1           1                                   Factual Places        
10          0                                     Oil and Lube       9
100         0                                    Psychiatrists      83
101         0                                     Radiologists      83
102         0                                      Respiratory      83
103         0                                       Urologists      83
104         0                                      Podiatrists      62
105         0                      Pregnancy and Sexual Health      62
106         0                    Weight Loss and Nutritionists      62
107         0                                        Landmarks       1
108         0                         Buildings and Structures     107
109         0                                          Gardens     107
11          0                                       Smog Check       9
110         0                     Historic and Protected Sites     107
111         0                          Monuments and Memorials     107
112         0                                          Natural     107
113         0                                          Beaches     112
114         0                                        Mountains     112
115         0                                          Forests     112
116         0                                            Lakes     112
117         0                                           Rivers     112
118         0                                            Parks     107
119         0                                    Natural Parks     118
12          0                                            Tires       9
120         0                                     Picnic Areas     118
121         0                                      Playgrounds     118
122         0                                      Urban Parks     118
123         0                                           Retail       1
124         0                                            Adult     123
125         0                                         Antiques     123
..        ...                                              ...     ...
72          0  Holistic, Alternative and Naturopathic Medicine      62
73          0                                      Acupuncture      72
74          0           Hospitals, Clinics and Medical Centers      62
75          0                        Medical Supplies and Labs      62
76          0                                    Mental Health      62
77          0                           Counseling and Therapy      76
78          0                                    Psychologists      76
79          0                                           Nurses      62
8           0                          Classic and Antique Car       2
80          0                                       Pharmacies      62
81          0              Physical Therapy and Rehabilitation      62
82          0                                  Sports Medicine      81
83          0                                       Physicians      62
84          0                                Anesthesiologists      83
85          0                                    Cardiologists      83
86          0                                   Dermatologists      83
87          0                             Ear, Nose and Throat      83
88          0                                  Family Medicine      83
89          0                              Gastroenterologists      83
9           0                           Maintenance and Repair       2
90          0                                  General Surgery      83
91          0                                Internal Medicine      83
92          0                                     Neurologists      83
93          0                  Obstetricians and Gynecologists      83
94          0                

## Load data crawled with Factual API

### Lausanne

In [3]:
lausanne_raw = pd.read_pickle(root + 'lausanne_crawled.pickle')
lausanne_raw_geo = gpd.GeoDataFrame(lausanne_raw, geometry="geometry")
lausanne_raw_geo

address     category_ids  \
0                          Rue du Grand-Chêne 7-9            [436]   
1                          Place Saint-François 2  [347, 341, 342]   
2                                  Rue Centrale 4  [347, 341, 312]   
3                            Avenue Sainte-Luce 1            [436]   
4                                 Rue Centrale 15             [80]   
5                          Place Saint-François 1       [342, 347]   
6                                   Rue Pepinet 3            [347]   
7                            Rue du Grand-Chêne 7       [356, 341]   
8                         Place Saint-François 15             [51]   
9                                 Place Pépinet 3            [142]   
10                      Escaliers du Grand-Pont 3       [355, 457]   
11                          Rue du Petit-Chêne 10       [347, 341]   
12                                 Rue du Pont 22       [347, 342]   
13                                Rue Centrale 12             [75]   
14                                 Rue Pépinet 3,            [347]   
15                                  Rue du Midi 4            [347]   
16                         Place Saint-François 1            [169]   
17                                 Rue du Midi 15             [47]   
18                             Rue de la Grotte 2       [347, 341]   
19                         Place Saint-François 5       [347, 341]   
20                      Rue du Petit-Saint-Jean 3            [130]   
21                          Rue du Petit-Chêne 28            [440]   
22                           Rue Saint-François 4            [265]   
23  Place Saint-François 15, Bâtiment de la Poste             [80]   
24                                 Rue Centrale 9            [268]   
25                         Place Saint-François 8            [144]   
26                          Rue du Petit-Chêne 20            [159]   
27                           Rue du Grand-Chêne 1             [80]   
28                         Place Saint-François 1             [80]   
29                           Rue du Grand-Pont 2B            [310]   
..                                            ...              ...   
5                             Rue de la Mouline 4            [419]   
6                         Chemin des Berges 12-14              NaN   
7                             Rue de la Mouline 8            [357]   
8                             Chemin des Berges 2            [419]   
9                             Rue de la Mouline 4             [23]   
10                            Rue de la Mouline 8            [347]   
11                            Chemin des Berges 4            [280]   
12                               Ch. des Berges 2            [460]   
13                         Avenue de la Mouline 4            [177]   
0                                       Unicentre             [29]   
0                              Route Cantonale 19            [436]   
1                           Chemin de Champagne 1             [23]   
2                              Route Cantonale 19            [293]   
3                                             NaN            [436]   
4                        Chemin du Champ-du-Lac 1            [274]   
5                          Chemin de Champagne 1A             [23]   
6                        Chemin du Champ-du-Lac 1             [80]   
7                                 Route Cantonale              NaN   
8                             Ch. Champ du Lac 19            [220]   
9                             Ch. de Champagne 1B            [130]   
0                         Chemin du Petit-Port 11            [364]   
1                                             NaN            [347]   
2                        Chemin du Champ-du-Lac 9              NaN   
3                            Chemin du Petit-Port              NaN   
4                                             NaN            [121]   
5                         Champagne, chemin de 15   

In [4]:
#Since we covered area greater than Lausanne we need to limit crawled data to Lausanne only

lausanne_geo = lausanne_raw_geo[lausanne_raw_geo['locality'] == 'Lausanne']
lausanne_geo.shape

(13560, 30)

In [5]:
lausanne_geo

address     category_ids  \
0                          Rue du Grand-Chêne 7-9            [436]   
1                          Place Saint-François 2  [347, 341, 342]   
2                                  Rue Centrale 4  [347, 341, 312]   
3                            Avenue Sainte-Luce 1            [436]   
4                                 Rue Centrale 15             [80]   
5                          Place Saint-François 1       [342, 347]   
6                                   Rue Pepinet 3            [347]   
7                            Rue du Grand-Chêne 7       [356, 341]   
8                         Place Saint-François 15             [51]   
9                                 Place Pépinet 3            [142]   
10                      Escaliers du Grand-Pont 3       [355, 457]   
11                          Rue du Petit-Chêne 10       [347, 341]   
12                                 Rue du Pont 22       [347, 342]   
13                                Rue Centrale 12             [75]   
14                                 Rue Pépinet 3,            [347]   
15                                  Rue du Midi 4            [347]   
16                         Place Saint-François 1            [169]   
17                                 Rue du Midi 15             [47]   
18                             Rue de la Grotte 2       [347, 341]   
19                         Place Saint-François 5       [347, 341]   
20                      Rue du Petit-Saint-Jean 3            [130]   
21                          Rue du Petit-Chêne 28            [440]   
22                           Rue Saint-François 4            [265]   
23  Place Saint-François 15, Bâtiment de la Poste             [80]   
24                                 Rue Centrale 9            [268]   
25                         Place Saint-François 8            [144]   
26                          Rue du Petit-Chêne 20            [159]   
27                           Rue du Grand-Chêne 1             [80]   
28                         Place Saint-François 1             [80]   
29                           Rue du Grand-Pont 2B            [310]   
..                                            ...              ...   
1                                             NaN              NaN   
2                                             NaN            [168]   
0                                             NaN            [113]   
16                                            NaN              NaN   
0                   Chemin Bois de la Chandelar 3              [2]   
1                              Route de Berne 301            [417]   
2                              Route de Berne 301       [358, 342]   
3                               Route de Cojonnex            [373]   
4           C/o Chalet-à-Gobet Route de Berne 301              [2]   
7                          Chemin d'Entre-Bois 23            [193]   
16                            Avenue de la Gare 4            [193]   
1                    Galeries Benjamin-Constant 1            [200]   
9                                    Planchette 1            [149]   
0                Rue de l'Industrie 23 - Crissier            [436]   
18                                            NaN            [118]   
0                                         Dorigny             [29]   
1                                         Dorigny              NaN   
2                                      Université              NaN   
3                                      Université              NaN   
0                                             NaN              NaN   
1           Université de Lausanne - Quartier Lac              NaN   
8                                             NaN            [248]   
0                               Route du Jorat 52            [177]   
1                               Route du Jorat 57             [26]   
0     Chalet des Monts de Pully, LAUSANNE 1000-27             [26]   
0                                Route de Marin 5   

In [6]:
lausanne_geo.columns

Index(['address', 'category_ids', 'category_labels', 'country',
       'edge_attributes.address', 'edge_attributes.address_extended',
       'edge_attributes.locality', 'edge_attributes.postcode', 'email',
       'factual_id', 'fax', 'geometry', 'hours', 'hours.friday',
       'hours.monday', 'hours.saturday', 'hours.sunday', 'hours.thursday',
       'hours.tuesday', 'hours.wednesday', 'hours_display', 'latitude',
       'locality', 'longitude', 'name', 'neighborhood', 'postcode', 'region',
       'tel', 'website'],
      dtype='object')

In [7]:
#Check for NaN in geometry
lausanne_geo['geometry'].isnull().values.any()

False

In [8]:
#lausanne_geo.drop_duplicates(['latitude','longitude'], keep='last')

In [9]:
#Check for NaN in geometry
#lausanne_geo.groupby('country').count()
#lausanne_geo['address'].value_counts()
#lausanne_geo['geometry'].value_counts()

In [10]:
#Clean index
lausanne_geo = lausanne_geo.reset_index(drop=True)

### Zürich

In [11]:
zurich_raw = pd.read_pickle(root + 'zurich_crawled.pickle')
zurich_raw_geo = gpd.GeoDataFrame(zurich_raw, geometry="geometry")
zurich_raw_geo

address address_extended category_ids  \
0                           Bahnhofstrasse 75              NaN        [141]   
1                           Schweizergasse 11              NaN   [143, 146]   
2                              Seidengasse 12              NaN        [221]   
3                             Gessnerallee 36              NaN         [35]   
4                         Lintheschergasse 21              NaN         [73]   
5                           Schweizergasse 10              NaN          NaN   
6                             Löwenstrasse 42              NaN          NaN   
7                             Löwenstrasse 49              NaN   [340, 347]   
8                            Schützengasse 23              NaN         [35]   
9                               Seidengasse 6              NaN         [35]   
10                           Usteristrasse 10              NaN        [440]   
11                          Schweizergasse 11              NaN        [123]   
12                            Löwenstrasse 42              NaN         [83]   
13  Bahnhofplatz 9 / Eing. Linth Escher Gasse              NaN        [159]   
14                           Usteristrasse 12              NaN        [142]   
15                            Löwenstrasse 57              NaN        [133]   
16                            Löwenstrasse 54              NaN        [219]   
17                            Löwenstrasse 35              NaN        [142]   
18                          Bahnhofstrasse 72              NaN        [274]   
19                           Usteristrasse 11              NaN        [274]   
20                            Löwenstrasse 65              NaN         [83]   
21                              Gerbergasse 7              NaN        [144]   
22                             Seidengasse 16              NaN        [142]   
23                        Schützengasse 22-24              NaN        [221]   
24                            Löwenstrasse 55              NaN         [69]   
25                           Uraniastrasse 10              NaN        [145]   
26                           Schützengasse 32              NaN        [347]   
27                            Gessnerallee 36              NaN        [280]   
28                             Seidengasse 18              NaN        [279]   
29                           Schweizergasse 8              NaN        [280]   
..                                        ...              ...          ...   
7                         Alte Bergstrasse 92              NaN         [26]   
8                              Feldstrasse 47              NaN          NaN   
9                              Ackerstrasse 5              NaN        [347]   
10                             Feldstrasse 48              NaN        [460]   
11                          Holzwiesstrasse 8              NaN        [133]   
12                           Feldstrasse 24 B              NaN        [181]   
13                                Im Büeler 7              NaN        [178]   
14                                Im Büeler 7              NaN        [274]   
15                            Ackerstrasse 13              NaN        [177]   
16                                Im Büeler 7              NaN        [274]   
17                            Ackerstrasse 25              NaN        [148]   
18                             Ackerstrasse 1              NaN        [236]   
0                             Bergstrasse 123              NaN        [293]   
1                                  Sportweg 8              NaN         [37]   
2                             Bergstrasse 121              NaN        [177]   
3                             Bergstrasse 120              NaN        [259]   
4                        Langackerstrasse 178              NaN        [292]   
5                             Bergstrasse 124              NaN        [292]   
6                             Bergstrasse 114              NaN        [177]   
7        

In [12]:
#Since we covered area greater than Lausanne we need to limit crawled data to Zürich only

zurich_geo = zurich_raw_geo[zurich_raw_geo['locality'] == 'Zürich']
zurich_geo.shape

(44758, 31)

In [13]:
#Check for NaN in geometry
zurich_geo['geometry'].isnull().values.any()

False

In [14]:
zurich_geo = zurich_geo.reset_index(drop=True)

# Loading Neighborhood data into Dataframes

In [15]:
file_lausanne = "./data/quartiers_lausanne.geojson"
file_zurich = "./data/quartiers_zurich.geojson"

neighborhood_lausanne = gpd.read_file(file_lausanne)
neighborhood_zurich = gpd.read_file(file_zurich)

print(type(neighborhood_lausanne))

neighborhood_lausanne

<class 'geopandas.geodataframe.GeoDataFrame'>


NOMQUARTIER NUMQUARTIER                              Name  \
0                                                         01 - Centre\n   
1                                               02 - Maupas / Valency\n   
2        Sébeillon/Malley         3\n         03 - Sébeillon / Malley\n   
3    Montoie/Bourdonnette           4     04 - Montoie / Bourdonnette\n   
4          Montriond/Cour           5           05 - Montriond / Cour\n   
5         Sous-Gare/Ouchy           6            06 - Sous-Gare / Ouchy   
6              Montchoisi           7                 07 - Montchoisi\n   
7      Florimont/Chissiez           8       08 - Florimont / Chissiez\n   
8     Mousquines/Bellevue           9      09 - Mousquines / Bellevue\n   
9          Vallon/Béthusy          10           10 - Vallon / Béthusy\n   
10       Chailly/Rovéréaz          11         11 - Chailly / Rovéréaz\n   
11  Sallaz/Vennes/Séchaud          12  12 - Sallaz / Vennes / Séchaud\n   
12             Sauvabelin          13                13 -  Sauvabelin\n   
13        Borde/Bellevaux          14          14 - Borde / Bellevaux\n   
14         Vinet/Pontaise          15           15 - Vinet / Pontaise\n   
15    Bossons/Blécherette          16      16 - Bossons / Blécherette\n   
16    Beaulieu/Grey/Boisy          17    17 - Beaulieu / Grey / Boisy\n   
17         Zones foraines          90             90 - Zones foraines\n   

   altitudeMode begin                                        description  \
0          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
1          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
2          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
3          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
4          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
5          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
6          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
7          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
8          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
9          None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
10         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
11         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
12         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
13         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
14         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
15         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
16         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
17         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   

   description2 drawOrder   end  extrude  \
0          None      None  None       -1   
1          None      None  None       -1   
2          None      None  None       -1   
3          None      None  None       -1   
4          None      None  None       -1   
5          None      None  None       -1   
6          None      None  None       -1   
7          None      None  None       -1   
8          None      None  None       -1   
9          None      None  None       -1   
10         None      None  None       -1   
11         None      None  None       -1   
12         None      None  None       -1   
13         None      None  None       -1   
14         None      None  None       -1   
15         None      None  None       -1   
16         None      None  None       -1   
17         None      None  None       -1   

                                             geometry  icon  tessellate  \
0   POLYGON Z ((6.63867 46.519814 0, 6.638932 46.5...  None          -1   
1   POLYGON Z ((6.613409 46.527202 0, 6.613878 46....  None          -1   
2   POLYGON Z ((6.620223 46.525428 0, 6.619146 46....  None          -1   
3   PO

In [16]:
neighborhood_zurich

Kreisname Kreisnummer          Quartiername Quartiernummer  \
0    Kreis 7           7            Hirslanden             73   
1    Kreis 8           8               Weinegg             83   
2    Kreis 8           8             Mühlebach             82   
3    Kreis 8           8               Seefeld             81   
4    Kreis 2           2           Wollishofen             21   
5    Kreis 2           2              Leimbach             23   
6    Kreis 4           4                  Werd             41   
7    Kreis 3           3              Sihlfeld             34   
8    Kreis 9           9           Albisrieden             91   
9    Kreis 7           7             Hottingen             72   
10   Kreis 2           2                  Enge             24   
11   Kreis 4           4           Langstrasse             42   
12   Kreis 5           5           Escher Wyss             52   
13   Kreis 7           7               Witikon             74   
14   Kreis 4           4                  Hard             44   
15   Kreis 1           1             Lindenhof             13   
16  Kreis 10          10             Wipkingen            102   
17   Kreis 6           6           Unterstrass             61   
18  Kreis 10          10                 Höngg            101   
19  Kreis 11          11              Oerlikon            115   
20  Kreis 11          11             Affoltern            111   
21   Kreis 1           1                  City             14   
22   Kreis 1           1               Rathaus             11   
23   Kreis 7           7              Fluntern             71   
24   Kreis 6           6            Oberstrass             63   
25  Kreis 12          12               Saatlen            121   
26  Kreis 11          11               Seebach            119   
27   Kreis 3           3           Friesenberg             33   
28   Kreis 1           1           Hochschulen             12   
29   Kreis 9           9            Altstetten             92   
30  Kreis 12          12            Hirzenbach            123   
31  Kreis 12          12  Schwamendingen-Mitte            122   
32   Kreis 3           3          Alt-Wiedikon             31   
33   Kreis 5           5         Gewerbeschule             51   

                                             geometry  
0   POLYGON ((8.55670119166035 47.3640651794388, 8...  
1   POLYGON ((8.556705417978661 47.3640463835363, ...  
2   POLYGON ((8.554234120938199 47.3645567121916, ...  
3   POLYGON ((8.54794601144437 47.3650049645305, 8...  
4   POLYGON ((8.5429738675001 47.335431756782, 8.5...  
5   POLYGON ((8.518104137500281 47.3442484810979, ...  
6   POLYGON ((8.53300513493766 47.3739425854604, 8...  
7   POLYGON ((8.519370463949629 47.3747817124699, ...  
8   POLYGON ((8.501270821270991 47.3796116903516, ...  
9   POLYGON ((8.583462441744061 47.3883106835516, ...  
10  POLYGON ((8.53585453953044 47.3520945610338, 8...  
11  POLYGON ((8.517531041657939 47.3853471294337, ...  
12  POLYGON ((8.51744858296067 47.3853694160862, 8...  
13  POLYGON ((8.601854623707929 47.3718582445828, ...  
14  POLYGON ((8.51617828297757 47.3839641947237, 8...  
15  POLYGON ((8.539674868492879 47.3659501499475, ...  
16  POLYGON ((8.52717336657194 47.4066831472077, 8...  
17  POLYGON ((8.52688268457328 47.4070859393208, 8...  
18  POLYGON ((8.525410488835339 47.4061730552798, ...  
19  POLYGON ((8.547463659118041 47.3993834671511, ...  
20  POLYGON ((8.53261057133672 47.416216937398, 8....  
21  POLYGON ((8.54198109696077 47.3767770406623, 8...  
22  POLYGON ((8.54241760888047 47.3666427548824, 8...  
23  POLYGON ((8.58215101738374 47.3878750508752, 8...  
24  POLYGON ((8.56819163610942 47.3913593507826, 8...  
25  POLYGON ((8.56324621854831 47.415646018331, 8....  
26  POLYGON ((8.527912004303859 47.4326009981247, ...  
27  POLYGON ((8.519433363304371 47.3512532243216, ...  
28  POLYGON ((8.550737497428861 47.3723392842336, ...  
29  POLYGON ((8.49896515456091 47.3903875668026

# Compute the area of each neighborhood

In [17]:
# Lausanne area
neighborhood_lausanne = neighborhood_lausanne.to_crs({'init': 'epsg:32633'})
neighborhood_lausanne["area"] = neighborhood_lausanne['geometry'].area/ 10**6 # km^2
neighborhood_lausanne = neighborhood_lausanne.to_crs({'init': 'epsg:4326'})
neighborhood_lausanne.head()

NOMQUARTIER NUMQUARTIER                           Name  \
0                                                    01 - Centre\n   
1                                          02 - Maupas / Valency\n   
2      Sébeillon/Malley         3\n      03 - Sébeillon / Malley\n   
3  Montoie/Bourdonnette           4  04 - Montoie / Bourdonnette\n   
4        Montriond/Cour           5        05 - Montriond / Cour\n   

  altitudeMode begin                                        description  \
0         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
1         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
2         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
3         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   
4         None  None  http://www.lausanne.ch/lausanne-officielle/sta...   

  description2 drawOrder   end  extrude  \
0         None      None  None       -1   
1         None      None  None       -1   
2         None      None  None       -1   
3         None      None  None       -1   
4         None      None  None       -1   

                                            geometry  icon  tessellate  \
0  POLYGON Z ((6.63867 46.51981399999999 0, 6.638...  None          -1   
1  POLYGON Z ((6.613409000000003 46.5272019999999...  None          -1   
2  POLYGON Z ((6.620222999999999 46.5254279999999...  None          -1   
3  POLYGON Z ((6.586363999999998 46.5238649999999...  None          -1   
4  POLYGON Z ((6.604343 46.51709799999999 0, 6.60...  None          -1   

  timestamp  visibility      area  
0      None          -1  1.254503  
1      None          -1  0.810437  
2      None          -1  1.048310  
3      None          -1  1.758095  
4      None          -1  1.457760

In [18]:
# Zurich area
neighborhood_zurich = neighborhood_zurich.to_crs({'init': 'epsg:32633'})
neighborhood_zurich["area"] = neighborhood_zurich['geometry'].area/ 10**6 # km^2
neighborhood_zurich = neighborhood_zurich.to_crs({'init': 'epsg:4326'})
neighborhood_zurich.head()

Kreisname Kreisnummer Quartiername Quartiernummer  \
0   Kreis 7           7   Hirslanden             73   
1   Kreis 8           8      Weinegg             83   
2   Kreis 8           8    Mühlebach             82   
3   Kreis 8           8      Seefeld             81   
4   Kreis 2           2  Wollishofen             21   

                                            geometry      area  
0  POLYGON ((8.55670119166035 47.3640651794388, 8...  2.197764  
1  POLYGON ((8.556705417978661 47.36404638353631,...  1.753914  
2  POLYGON ((8.554234120938201 47.36455671219159,...  0.640998  
3  POLYGON ((8.547946011444369 47.3650049645305, ...  2.435484  
4  POLYGON ((8.542973867500102 47.33543175678199,...  5.809536

# Joining places with neighborhoods

In [19]:
from geopandas.tools import sjoin

# Compare CRS metrics
print('CRS places: ', lausanne_geo.crs)
print('CRS neigborhood: ', neighborhood_lausanne.crs)

CRS places:  None
CRS neigborhood:  {'init': 'epsg:4326'}


In [ ]:
lausanne_geo.crs = neighborhood_lausanne.crs
print('CRS places: ', lausanne_geo.crs)
print('CRS neigborhood: ', neighborhood_lausanne.crs)

joined_lausanne = sjoin(lausanne_geo, neighborhood_lausanne, how='left')
grouped_lausanne = joined_lausanne.groupby('index_right')


In [21]:
# Aggregate Lausanne
cat_list_lausanne = grouped_lausanne['category_ids'].aggregate(lambda x: list(x))
cat_list_lausanne = cat_list_lausanne.reset_index(drop=True)
cat_list_lausanne


0     [[436], [347, 341, 342], [347, 341, 312], [436...
1     [[195], [311], nan, [181], [443], [189], [238]...
2     [nan, [225], [457], nan, [440], [357], [2], [3...
3     [[420], [244], [288], [221], [272], [213], [23...
4     [[436], [440], [143], [188], [47], [107, 55], ...
5     [[347, 342, 341], [436], [436], [190], [145], ...
6     [[143, 145], [143], [280], nan, [253], nan, [2...
7     [[47], nan, [310], [144], nan, [20], [236], [2...
8     [[314], [239], nan, [189], [372], [314], [320,...
9     [[71], [47], [415], [20], [188], [47], [239], ...
10    [[272], [239], nan, [308], [179], [292], [193]...
11    [[212], [347], nan, [363], [83], [280], nan, [...
12    [[292], [333], [107, 20], [116], [387], [347],...
13    [[72], [236], nan, [62], [137], [253], [62], [...
14    [[347], [29], [167], [44], [347], [279], [280]...
15    [[51], [66], [280], [221], [20], [34], nan, [3...
16    [[280], [347], [312, 347], [177], [47], nan, [...
17    [[292], [277], nan, nan, [342], [125], nan

In [22]:
# Join Zürich

# Compare CRS metrics
print('CRS places: ', zurich_geo.crs)
print('CRS neigborhood: ', neighborhood_zurich.crs)

CRS places:  None
CRS neigborhood:  {'init': 'epsg:4326'}


In [ ]:
zurich_geo.crs = neighborhood_zurich.crs
print('CRS places: ', zurich_geo.crs)
print('CRS neigborhood: ', neighborhood_zurich.crs)

joined_zurich = sjoin(zurich_geo, neighborhood_zurich, how='left')
grouped_zurich = joined_zurich.groupby('index_right')


In [24]:
# Aggregate zurich
cat_list_zurich = grouped_zurich['category_ids'].aggregate(lambda x: list(x))
cat_list_zurich = cat_list_zurich.reset_index(drop=True)
cat_list_zurich


0     [[83], [137], [288], [193], [83], nan, [82], n...
1     [[347], [103], [149], nan, [106], [220], [340]...
2     [[347, 312], [26], [29], [347], [100], [280], ...
3     [[436], [436], [436], [436], [347], [347], [31...
4     [[157], [181], [238], [213], nan, [178], [460]...
5     [[177], [244], [83], [177], [306], nan, [274],...
6     [[436], [347], [355], [213], [219], [98], [35]...
7     [[272], [189], nan, [429], [408], [280], [347]...
8     [[407], [450], [129], [149], [163], [150], [13...
9     [[220], [310], [332], [358, 312], [73], [81], ...
10    [[288], [274], nan, [221], [220], [222], [293]...
11    [[355], [347], [429], [171], [317], nan, [177]...
12    [[311, 107], [347], [311], [348], [347], [162]...
13    [nan, [178], [274], [296], nan, [236], [336], ...
14    [[150], [123], nan, [207], [20], [306], [211],...
15    [[274], [144], [144], [143], [143], [80], [47]...
16    [[342, 347], [129], [83], nan, [157], [2], [34...
17    [[280], [220], nan, [236], [220], [20], [8

# Creating descriptors for neighborhoods

In [25]:
LABEL_LENGTH = 467

def create_descriptor(nested_array):
    label_freq = np.zeros(LABEL_LENGTH)
    for sublist in nested_array:
        if type(sublist) is not list:
            continue
        for item in sublist:
            label_freq[item] += 1
    return label_freq

freq_lausanne = cat_list_lausanne.apply(create_descriptor)
print(freq_lausanne)

freq_zurich = cat_list_zurich.apply(create_descriptor)
print(freq_zurich)

0     [0.0, 0.0, 25.0, 0.0, 4.0, 0.0, 0.0, 1.0, 0.0,...
1     [0.0, 0.0, 12.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,...
2     [0.0, 0.0, 35.0, 0.0, 4.0, 0.0, 3.0, 1.0, 0.0,...
3     [0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
4     [0.0, 0.0, 5.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...
5     [0.0, 0.0, 12.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,...
6     [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7     [0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, ...
8     [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9     [0.0, 0.0, 9.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
10    [0.0, 0.0, 3.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...
11    [0.0, 0.0, 11.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,...
12    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
13    [0.0, 0.0, 18.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,...
14    [0.0, 0.0, 11.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,...
15    [0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
16    [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
17    [0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0

In [26]:
print(freq_lausanne[0])
print(freq_zurich[0])

[   0.    0.   25.    0.    4.    0.    0.    1.    0.    7.    0.    0.
    0.    0.    4.    0.    0.    0.    0.    0.   36.    1.    0.    8.
    0.    2.   75.   14.   11.   15.    0.    0.    3.    0.    6.   25.
    2.    3.    0.    0.    0.    0.    0.    7.   12.    1.    0.   94.
    0.    1.    0.   20.    0.    0.    0.   15.    0.    0.    0.    0.
    3.    0.  102.    0.    0.    0.    2.    0.    4.  133.    0.    2.
   14.   29.   14.   10.    0.   11.   17.    3.   47.   37.    2.  315.
    0.    1.    0.    0.    0.    0.    0.   54.    2.    8.    0.   17.
    0.    0.    5.    0.  187.    0.    0.    7.    1.    0.   12.    3.
    3.    2.    2.    0.    0.    1.    0.    0.    0.    0.    6.    0.
    0.    0.    1.   28.    1.   22.    1.    0.   20.    4.   33.    3.
    8.   32.    1.    2.    0.    9.    1.    0.    0.    3.  108.  135.
   59.   32.    0.    0.    8.   20.    5.    2.    3.    7.    0.    0.
    0.   17.    7.   22.    2.    0.   16.   27.   

### All places

In [27]:
#Normalize descriptor vectors
from sklearn.preprocessing import normalize

def create_descriptor(frequencies, area):
    descriptor = frequencies / area
    descriptor_matrix = descriptor.as_matrix()
    descriptor_matrix = np.vstack(descriptor_matrix)
    descriptor_matrix_normalized = normalize(descriptor_matrix, axis=1, norm='l2')
    
    return descriptor_matrix_normalized

In [28]:
all_lausanne = create_descriptor(freq_lausanne, neighborhood_lausanne['area'].values)

In [29]:
all_zurich = create_descriptor(freq_zurich, neighborhood_zurich['area'].values)

In [30]:
import collections
def flatten(x):
    if isinstance(x, collections.Iterable):
        return [a for i in x for a in flatten(i)]
    else:
        return [x]

def category_and_all_subs(categories_df, category_ids):
    category_list = [] + category_ids
    childs_list = []
    while True:
        childs_list = category_list
        new_childs_list = []
        for cat_id in childs_list:
            childs = list(categories[categories["parents"] == str(cat_id)].index)
            if childs:
                new_childs_list += childs

        childs_list = list(set(new_childs_list) - set(category_list))
        category_list += childs_list
        category_list = flatten(category_list)
            
        if not childs_list:
            break
    return category_list

def selected_frequencies(row, frequencies):
    selected_frequencies = row[frequencies]
    return selected_frequencies

### Landmarks

In [31]:
landmarks_ids = category_and_all_subs(categories, [107])

for cat_id in landmarks_ids:
    print(categories.loc[cat_id]['label'])

Landmarks
Buildings and Structures
Gardens
Historic and Protected Sites
Monuments and Memorials
Natural
Parks
Dog Parks
Beaches
Mountains
Forests
Lakes
Rivers
Natural Parks
Picnic Areas
Playgrounds
Urban Parks


In [32]:
landmarks_freq_lausanne = freq_lausanne.apply(lambda x: selected_frequencies(x, landmarks_ids))
landmarks_freq_zurich = freq_zurich.apply(lambda x: selected_frequencies(x, landmarks_ids))

In [33]:
landmarks_freq_lausanne = freq_lausanne.apply(lambda x: selected_frequencies(x, landmarks_ids))
landmarks_freq_zurich = freq_zurich.apply(lambda x: selected_frequencies(x, landmarks_ids))

landmarks_lausanne = create_descriptor(landmarks_freq_lausanne, neighborhood_lausanne['area'].values)
landmarks_zurich = create_descriptor(landmarks_freq_zurich, neighborhood_zurich['area'].values)

### Fast foods

In [34]:
fast_food_ids = category_and_all_subs(categories, [351, 355, 363, 366]) #burgers, fast_food, pizza, sushi

for cat_id in fast_food_ids:
    print(categories.loc[cat_id]['label'])

Burgers
Fast Food
Pizza
Sushi


In [35]:
fastfood_freq_lausanne = freq_lausanne.apply(lambda x: selected_frequencies(x, fast_food_ids))
fastfood_freq_zurich = freq_zurich.apply(lambda x: selected_frequencies(x, fast_food_ids))

fastfood_lausanne = create_descriptor(fastfood_freq_lausanne, neighborhood_lausanne['area'].values)
fastfood_zurich = create_descriptor(fastfood_freq_zurich, neighborhood_zurich['area'].values)

### Travel spots

In [36]:
travel_ids = category_and_all_subs(categories, [430])

for cat_id in travel_ids:
    print(categories.loc[cat_id]['label'])

Travel
Lodging
Cruises
Travel Agents and Tour Operators
Tourist Information and Services
Bed and Breakfasts
Cottages and Cabins
Hostels
Hotels and Motels
Lodges and Vacation Rentals
Resorts


In [37]:
travel_freq_lausanne = freq_lausanne.apply(lambda x: selected_frequencies(x, travel_ids))
travel_freq_zurich = freq_zurich.apply(lambda x: selected_frequencies(x, travel_ids))

travel_lausanne = create_descriptor(travel_freq_lausanne, neighborhood_lausanne['area'].values)
travel_zurich = create_descriptor(travel_freq_zurich, neighborhood_zurich['area'].values)

### Sports

In [38]:
sports_ids = category_and_all_subs(categories, [372])

for cat_id in sports_ids:
    print(categories.loc[cat_id]['label'])

Sports and Recreation
Gymnastics
Gyms and Fitness Centers
Hockey
Outdoors
Paintball
Personal Trainers
Race Tracks
Racquet Sports
Recreation Centers
Running
Skating
Snow Sports
Soccer
Sports Clubs
Stadiums and Arenas
Swimming Pools
Water Sports
Yoga and Pilates
Athletic Fields
Baseball
Basketball
Combat Sports
Cycling
Dance
Equestrian
Football
Golf
Gun Ranges
Golf Courses
Campgrounds and RV Parks
Hiking
Hot Air Balloons
Hunting and Fishing
Rock Climbing
Skydiving
Surfing
Racquetball
Tennis
Batting Ranges
Boating
Canoes and Kayaks
Rafting
Scuba Diving
Swimming


In [39]:
sports_freq_lausanne = freq_lausanne.apply(lambda x: selected_frequencies(x, sports_ids))
sports_freq_zurich = freq_zurich.apply(lambda x: selected_frequencies(x, sports_ids))

sports_lausanne = create_descriptor(sports_freq_lausanne, neighborhood_lausanne['area'].values)
sports_zurich = create_descriptor(sports_freq_zurich, neighborhood_zurich['area'].values)

# Neighborhood mapping procedure

In order to find a best matching between a freely chosen neighborhood and its corresponding descriptor $\vec n_i^A$ from the origin city $A$ and a corresponding target neighborhood with descriptor $\vec n_j^B$ in the target city $B$ we will be mapping to the closest descriptor in the target city as follows:

$$ \| \vec n_i^A - \vec n_j^B \|^2 \leq  \| \vec n_i^A - \vec n_k^B \|^2  \quad \forall k \neq j $$

By expanding the above formula we can show that maximizing the dot product between neighborhood descriptors will actually result in the closest match for neighborhood $n_i$,

$$ (\vec n_i^A)^2 - 2 (\vec n_i^A)^T \vec n_j^B + (\vec n_j^B)^2  \leq  (\vec n_i^A)^2 - 2 (\vec n_i^A)^T \vec n_k^B + (\vec n_k^B)^2  $$

Since we have normalized the descriptor vectors above we have $ (\vec n_i^A)^2 = (\vec n_j^B)^2 = (\vec n_k^B)^2 = 1 \quad \forall i,j,k$ which leads to

$$ - 2 (\vec n_i^A)^T \vec n_j^B \leq - 2 (\vec n_i^A)^T \vec n_k^B  $$

Dividing the above inequation by $-2$ including the corresponding flip to the inequality sign results in

$$ (\vec n_i^A)^T \vec n_j^B \geq (\vec n_i^A)^T \vec n_k^B  $$

This shows that the closest neighborhood can be found be finding the maximal dot product between the chosen origin neighborhood descriptor and the set of target neighborhood descriptors $\vec n_j^B$.





In [40]:
def map_neighborhoods(lausanne_descriptor_matrix_normalized, zurich_descriptor_matrix_normalized):
    map_cities = lausanne_descriptor_matrix_normalized @ zurich_descriptor_matrix_normalized.T
    zurich_districts_in_lausanne = map_cities.argmax(axis=0)
    lausanne_districts_in_zurich = map_cities.argmax(axis=1)
    
    return lausanne_districts_in_zurich, zurich_districts_in_lausanne

### All places

In [41]:
lausanne_districts_in_zurich_all, zurich_districts_in_lausanne_all = map_neighborhoods(all_lausanne, all_zurich)

In [42]:
lausanne_districts_in_zurich_all

array([28, 19, 19, 27,  7, 19, 23,  9,  2, 19, 19, 19, 11, 29,  1, 26,  7,
       29])

In [43]:
zurich_districts_in_lausanne_all

array([ 7, 14,  8,  8,  5, 15,  5,  5, 15,  7,  8,  5,  8, 10,  1,  0,  2,
        5, 11,  1, 13,  0,  0,  7,  7, 11, 11,  3,  0, 13, 13, 13,  4,  4])

### Landmarks 

In [44]:
lausanne_districts_in_zurich_landmarks, zurich_districts_in_lausanne_landmarks = map_neighborhoods(landmarks_lausanne, landmarks_zurich)

In [45]:
lausanne_districts_in_zurich_landmarks

array([17, 14,  6, 14, 33, 15, 14,  0,  2,  8, 14, 22,  8, 23,  6,  2, 14,
        0])

In [46]:
zurich_districts_in_lausanne_landmarks

array([ 1, 13, 15, 13,  5,  0, 14,  0,  9,  9,  0,  0, 15,  9,  1,  5,  1,
        0, 14,  1,  9, 15, 14, 13,  1, 13, 15,  0,  1,  0,  0,  1,  9,  0])

### Fast food

In [47]:
lausanne_districts_in_zurich_fastfood, zurich_districts_in_lausanne_fastfood = map_neighborhoods(fastfood_lausanne, fastfood_zurich)

In [48]:
lausanne_districts_in_zurich_fastfood

array([18, 33, 28, 20,  3, 17,  0,  0,  0,  3, 14,  4,  0, 24, 25, 14, 21,
        0])

In [49]:
zurich_districts_in_lausanne_fastfood

array([ 6,  6,  1,  4, 13,  6, 13,  3,  6,  0,  5, 10, 13,  0, 10,  1,  6,
        5,  0, 13,  3,  2,  2,  6, 13,  0,  3,  6,  2, 13,  6,  4, 10,  1])

### Travel spots

In [50]:
lausanne_districts_in_zurich_travel, zurich_districts_in_lausanne_travel = map_neighborhoods(travel_lausanne, travel_zurich)

In [51]:
lausanne_districts_in_zurich_travel

array([32, 18,  8, 23, 20,  3, 24,  8, 30,  8, 16, 25,  0, 13,  8,  0,  0,
        0])

In [52]:
zurich_districts_in_lausanne_travel

array([15,  4,  4,  5,  5,  0,  4,  4,  2,  5,  5,  5,  4, 13,  4,  5,  0,
        4,  8, 11,  4, 11,  5,  6,  6, 11,  4,  6,  4,  2,  8,  8,  0,  5])

### Sports

In [53]:
lausanne_districts_in_zurich_sports, zurich_districts_in_lausanne_sports = map_neighborhoods(sports_lausanne, sports_zurich)

In [54]:
lausanne_districts_in_zurich_sports

array([33, 32, 11, 32, 22,  2,  0, 32, 32, 26, 22, 25, 25,  5,  0, 12,  6,
        9])

In [55]:
zurich_districts_in_lausanne_sports

array([ 0,  5,  5,  0,  4, 13, 16,  2,  5,  0,  5,  2,  2,  2, 16, 11,  5,
       11,  2,  2,  0,  5,  4,  0, 11, 11,  5, 13,  2,  2,  0, 13,  8,  0])